### ISSUE TITLE
Unilateral Sync Tables after Migration

### ISSUE THREAD

**Issue by giubari** [isapir/Migrate2Postgres#8]
Hi,
is possible to reuse the batch just to update the database\table after migration?

**Comment by isapir** [comment]
If you mean to do an incremental update then no, that feature is not supported at this time.

Running the `dml` command will copy all of the data over from the beginning.  Unless you have a really huge database that is usually done in a relatively short period of time, assuming no major network latency between the servers.

**Comment by giubari** [comment]
Ok thanks. We're talking about 200k rows but for now I'll stick to a
midnight run. Thanks for the quick reply.


Il giorno mer 2 gen 2019 alle ore 23:05 Igal Sapir <notifications@github.com>
ha scritto:

**Comment by isapir** [comment]
I have moved millions of rows in a matter of minutes, but if you want to minimize the downtime then you definitely want to plan for a time when usage is low and notify everyone ahead of time.
